application: flagxor
version: 1
runtime: go
api_version: go1

handlers:
- url: /test
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /favicon.ico
  static_files: static/4spire.ico
  upload: static/4spire.ico
- url: /favicon.png
  static_files: static/4spire.png
  upload: static/4spire.png
- url: /archive
  static_files: static/archive.html
  upload: static/archive.html
- url: /topics
  static_files: static/topics.html
  upload: static/topics.html
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
- url: /article/([^/]*)/?
  static_files: article/\1.html
  upload: article/(.*)
