runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
- url: /favicon.ico
  static_files: static/4spire.ico
  upload: static/4spire.ico
  secure: always
- url: /favicon.png
  static_files: static/4spire.png
  upload: static/4spire.png
  secure: always
- url: /archive
  static_files: static/archive.html
  upload: static/archive.html
  secure: always
- url: /topics
  static_files: static/topics.html
  upload: static/topics.html
  secure: always
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always
- url: /article/([^/]*)/?
  static_files: article/\1.html
  upload: article/(.*)
  secure: always
- url: /.well-known/acme-challenge/d6vUvFQiBZKnIk1Sh_amFgvYUlfOtOzZZf5xQKLU-gY
  static_files: auth/challenge
  upload: auth/challenge
- url: /google0879d6ce2b857a28.html
  static_files: auth/google0879d6ce2b857a28.html
  upload: auth/google0879d6ce2b857a28.html
- url: /test
  script: flagxor.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
